import createMDX from "@next/mdx";
import type { NextConfig } from "next";

/**
 * Static export only: `next build` writes a complete site to /out that any
 * ordinary static file server can host. There is no request-time server.
 *
 * NEXT_PUBLIC_BASE_PATH  "" for a custom domain or Vercel; "/repo-name" for a
 *                        GitHub Pages project site. Must start with "/" and
 *                        must not end with "/".
 */
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
if (basePath && !/^\/[A-Za-z0-9._~-]+(\/[A-Za-z0-9._~-]+)*$/.test(basePath)) {
  throw new Error(`NEXT_PUBLIC_BASE_PATH must look like "/repo-name" (got "${basePath}")`);
}

const nextConfig: NextConfig = {
  output: "export",
  // /companies/openai/ → /companies/openai/index.html, which static hosts
  // (including GitHub Pages) serve for deep links and refreshes.
  trailingSlash: true,
  basePath: basePath || undefined,
  // No request-time image optimizer exists in a static export. Responsive
  // derivatives are generated by scripts/prepare-images.mjs instead.
  images: { unoptimized: true },
  poweredByHeader: false,
  reactStrictMode: true,
  pageExtensions: ["ts", "tsx"],
};

const withMDX = createMDX({});

export default withMDX(nextConfig);
